version: '3.8'
services:
  rust-auth-service: 
    build:
      context: ../../ 
      dockerfile: deployments/docker/Dockerfile
      args:
        - DATABASE_URL=postgres://postgres:5up3rDup3r53cr3tP@55w0rd@host.docker.internal:5430/postgres
    container_name: rust-auth-service
    image: asia-southeast2-docker.pkg.dev/khhini-devops-2705/docker-repo/rust-auth-service
    environment:
      ENV: development
      PORT: 8080
      HOST: 0.0.0.0
      LOKI_HOST: loki
      LOKI_PORT: 3100
      RUST_BACKTRACE: full
      DATABASE_URL: postgres://postgres:5up3rDup3r53cr3tP@55w0rd@db:5432/postgres
      PWD_SECRET: SuperDuperSecret
    ports:
      - 8080:8080
    networks:
      - devops
    depends_on:
      - db
  db:
    image: postgres
    container_name: rust-auth-service-db
    environment:
      POSTGRES_PASSWORD: 5up3rDup3r53cr3tP@55w0rd
    networks:
      - devops
    ports:
      - 5430:5432

networks:
  devops:
    name: devops-net     
    external: true
